### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hjJunior** [hjJunior/flutter-easy-form#1]
# Roadmap

- [x] Must be easy to create custom fields
- [x] Must be able to have fields validations
- [x] Nice to have async validations
- [x] Must have the ability to access values from any child
- [x] Must have the ability to change field values from any child
- [x] Nice to have Flutter Web compatibility
- [x] Must have the ability to reset the form
- [x] Nice to have watch mode for fields

**Should be as smaller as possible**
- [ ] Must have additional packages for additional fields
- [ ] Must have an additional package for validation (**But it should be possible to create custom validations without this additional package**)

#### Basic fields
- [x] EasyTextField
- [ ] EasyCheckbox
- [ ] EasyCheckboxList
- [ ] EasyRadioButtonList

#### Additional fields
- [ ] EasySelect
- [ ] Location picker (Integration with Google Maps)
- [ ] File picker
- [ ] Color picker
- [ ] SignaturePad
- [ ] CountrySelector
- [ ] Date and time picker
- [ ] Slider / Price range
